app/urls.py
from django.urls import path
from .views import Create, Detail


urlpatterns = [
    path('create/', Create.as_view(), name='index'),
    path('user/<int:user_id>', Detail.as_view(), name='detail')
]

homework19/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    class Gender(models.TextChoices):
        MALE = 'M', 'Мужской'
        FEMALE = 'F', 'Женский'
        
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=20, choices=Gender.choices, default=Gender.MALE)
    

app/forms.py
from django import forms
from .models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('name', 'last_name', 'age', 'gender')

app/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView
from .models import User
from .forms import UserForm
from django.urls import reverse_lazy

# Create your views here.


class Create(CreateView):
    model = User
    template_name = 'index.html'
    form_class = UserForm
    success_url = reverse_lazy('index')

class Detail(DetailView):
    model = User
    template_name = 'detail.html'
    context_object_name = 'user'
    pk_url_kwarg = 'user_id'
    

app/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ user.name }}</h1>
    <h1>{{ user.last_name }}</h1>
    <h2>{{ user.age }}</h2>
    <h3>{{ user.get_gender_display }}</h3>
</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post">
        {% csrf_token %}

        {{ form }}

        <button type="submit">Создать пользователя</button>
    </form>
</body>
</html>